// AUTO-GENERATED FILE.
// This file is generated by `npm run precompute`.
// It is safe to commit, and it is safe to regenerate.

import type { PrecomputedTrackData } from './precomputed'

export const PRECOMPUTED_BY_TRACK: Record<string, PrecomputedTrackData> = {}


