// AUTO-GENERATED FILE.
// Generated by: npm run precompute
// Do not edit by hand.

import type { PrecomputedTrackData } from './precomputed'

export const PRECOMPUTED_BY_TRACK: Record<string, PrecomputedTrackData> = {
  "track-002": {
    "medals": {
      "bronzeMs": 26181,
      "silverMs": 22387,
      "goldMs": 18972
    },
    "coins": []
  },
  "track-003": {
    "medals": {
      "bronzeMs": 22319,
      "silverMs": 19084,
      "goldMs": 16173
    },
    "coins": []
  },
  "track-004": {
    "medals": {
      "bronzeMs": 18854,
      "silverMs": 16121,
      "goldMs": 13662
    },
    "coins": []
  },
  "track-005": {
    "medals": {
      "bronzeMs": 21164,
      "silverMs": 18096,
      "goldMs": 15336
    },
    "coins": []
  },
  "track-006": {
    "medals": {
      "bronzeMs": 29460,
      "silverMs": 25191,
      "goldMs": 21348
    },
    "coins": []
  },
  "track-007": {
    "medals": {
      "bronzeMs": 25908,
      "silverMs": 22153,
      "goldMs": 18774
    },
    "coins": []
  },
  "track-008": {
    "medals": {
      "bronzeMs": 29112,
      "silverMs": 24893,
      "goldMs": 21096
    },
    "coins": []
  },
  "track-009": {
    "medals": {
      "bronzeMs": 23374,
      "silverMs": 19987,
      "goldMs": 16938
    },
    "coins": []
  },
  "track-010": {
    "medals": {
      "bronzeMs": 25871,
      "silverMs": 22121,
      "goldMs": 18747
    },
    "coins": []
  },
  "track-011": {
    "medals": {
      "bronzeMs": 25921,
      "silverMs": 22164,
      "goldMs": 18783
    },
    "coins": []
  },
  "track-012": {
    "medals": {
      "bronzeMs": 23921,
      "silverMs": 20454,
      "goldMs": 17334
    },
    "coins": []
  },
  "track-001": {
    "medals": {
      "bronzeMs": 8818,
      "silverMs": 7540,
      "goldMs": 6390
    },
    "coins": []
  }
}
;
