import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

import { ALL_TRACKS, getTrackById } from '../src/game/track'
import { deriveMedalsFromBaseline, estimateIdealLine, generateCoinsFromIdealLine } from '../src/game/medals'

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)

const outFile = path.join(__dirname, '..', 'src', 'game', 'precomputed.generated.ts')

type PrecomputedTrackData = {
  medals: { bronzeMs: number; silverMs: number; goldMs: number }
  coins: Array<{ id: string; p: { x: number; y: number }; r: number }>
}

const run = () => {
  const out: Record<string, PrecomputedTrackData> = {}

  for (const t of ALL_TRACKS) {
    // Skip if missing (shouldn't happen) or if it already has authored medals+coins.
    const track = getTrackById(t.id)
    if (!track) continue

    // Compute ideal line (fastest found) and derive medals + coins.
    const line = estimateIdealLine(track, { budget: 220, seed: 1337 })
    if (!line) {
      throw new Error(`Failed to estimate ideal line for ${track.id}`)
    }
    const medals = deriveMedalsFromBaseline(line.timeMs)
    const coins = generateCoinsFromIdealLine(track, line)
    out[track.id] = { medals, coins }
    // eslint-disable-next-line no-console
    console.log(`${track.id}: baseline=${line.timeMs}ms gold=${medals.goldMs} coins=${coins.length}`)
  }

  const header =
    `// AUTO-GENERATED FILE.\n` +
    `// Generated by: npm run precompute\n` +
    `// Do not edit by hand.\n\n` +
    `import type { PrecomputedTrackData } from './precomputed'\n\n` +
    `export const PRECOMPUTED_BY_TRACK: Record<string, PrecomputedTrackData> = `

  const body = JSON.stringify(out, null, 2) + '\n'
  const footer = ';\n'

  fs.writeFileSync(outFile, header + body + footer, 'utf8')
  // eslint-disable-next-line no-console
  console.log(`Wrote ${outFile}`)
}

run()


